name: Publish

on:
  push:
    branches: [main]
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1

      - name: Publish (dry run)
        if: github.event_name == 'push'
        run: deno publish --dry-run

      - name: Publish
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: deno publish

      - name: Release to github
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
